"""Reporters: JSON, Markdown, and SARIF 2.1.0 output."""
from __future__ import annotations

from viperstrike.core import ScanResult

JSON_REPORT_SUFFIX = ".json"
MD_REPORT_SUFFIX = ".md"
SARIF_REPORT_SUFFIX = ".sarif"


def render_json(result: ScanResult) -> str:
    return result.to_json() + "\n"


def render_markdown(result: ScanResult) -> str:
    lines = []
    lines.append(f"# viperstrike audit report")
    lines.append("")
    lines.append(f"- **Target:** `{result.target}`")
    lines.append(f"- **Files scanned:** {result.files_scanned}")
    lines.append(f"- **Lines scanned:** {result.lines_scanned}")
    lines.append(f"- **Scan time:** {result.scan_time_ms:.1f} ms")
    summary = result.summary
    if summary:
        parts = ", ".join(f"{sev} {cnt}" for sev, cnt in sorted(summary.items()))
        lines.append(f"- **Findings:** {len(result.findings)} ({parts})")
    else:
        lines.append(f"- **Findings:** 0 (clean)")
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    if not result.findings:
        lines.append("No vulnerabilities detected in the audited source tree.\n")
    else:
        lines.append("| Rule | Severity | Confidence | Location | Message |")
        lines.append("|------|----------|------------|----------|---------|")
        for f in result.findings:
            loc = f.locations[0]
            loc_str = f"{loc.file}:{loc.line}"
            lines.append(f"| {f.rule_id} | {f.severity} | {f.confidence} | "
                         f"`{loc_str}` | {f.message} |")
        lines.append("")
        lines.append("## Detail")
        lines.append("")
        for i, f in enumerate(result.findings, 1):
            loc = f.locations[0]
            lines.append(f"### {f.rule_id} — {f.rule_name} (finding {i})")
            lines.append("")
            lines.append(f"- **Severity:** {f.severity} "
                         f"(offensive level: {f.severity_label})")
            lines.append(f"- **Confidence:** {f.confidence}")
            lines.append(f"- **Location:** `{loc.file}:{loc.line}`")
            if f.cwe:
                lines.append(f"- **CWE:** {f.cwe}")
            lines.append("")
            lines.append(f"**Message:** {f.message}")
            if f.evidence:
                lines.append("")
                lines.append("```python")
                lines.append(f.evidence)
                lines.append("```")
            if f.fix_suggestion:
                lines.append("")
                lines.append(f"**Fix:** {f.fix_suggestion}")
            lines.append("")
    if result.errors:
        lines.append("## Scan errors")
        lines.append("")
        for e in result.errors:
            lines.append(f"- {e}")
        lines.append("")
    lines.append("---")
    lines.append("*Generated by viperstrike (MCP Server Vulnerability Auditor).*")
    return "\n".join(lines) + "\n"


def render_sarif(result: ScanResult) -> str:
    import json

    rules_used = {}
    for f in result.findings:
        rules_used.setdefault(f.rule_id, {"name": f.rule_name, "cwe": f.cwe})

    driver_rules = []
    for rid in sorted(rules_used):
        info = rules_used[rid]
        entry = {
            "id": rid,
            "name": info["name"],
            "shortDescription": {"text": info["name"]},
            "fullDescription": {"text": info["name"]},
            "helpUri": f"https://github.com/5h4d0wn1k/viperstrike#detectors",
            "properties": {"tags": ["mcp", "security"]},
        }
        if info["cwe"]:
            entry["properties"]["tags"].append(info["cwe"])
        driver_rules.append(entry)

    results = []
    for f in result.findings:
        loc = f.locations[0]
        result_entry = {
            "ruleId": f.rule_id,
            "level": f.severity,
            "message": {"text": f.message},
            "locations": [
                {
                    "physicalLocation": {
                        "artifactLocation": {
                            "uri": loc.file,
                            "uriBaseId": "%SRCROOT%",
                        },
                        "region": {
                            "startLine": loc.line,
                            "startColumn": loc.column + 1,
                        },
                    }
                }
            ],
        }
        props = {"confidence": f.confidence}
        if f.evidence:
            props["evidence"] = f.evidence
        if f.fix_suggestion:
            props["fixSuggestion"] = f.fix_suggestion
        if f.cwe:
            props["cwe"] = f.cwe
        result_entry["properties"] = props
        results.append(result_entry)

    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "viperstrike",
                        "semanticVersion": "1.0.0",
                        "informationUri": "https://github.com/5h4d0wn1k/viperstrike",
                        "rules": driver_rules,
                    }
                },
                "invocations": [
                    {
                        "executionSuccessful": not result.errors,
                        "toolExecutionNotifications": [
                            {"message": {"text": e}}
                            for e in result.errors
                        ],
                    }
                ],
                "results": results,
            }
        ],
    }
    return json.dumps(sarif, indent=2) + "\n"